"""Constants used across the project."""
SELECTED_BOOKS = ['genesis',
                  'exodus',
                  'leviticus',
                  'deuteronomy',
                  'samuel',
                  'kings',
                  'daniel',
                  'chronicles',
                  'song_of_songs',
                  'ezra-nehemiah',
                  'ecclesiastes',
                  'judges',
                  'joshua',
                  'esther']

KJ_MAPPER = {'Gen': 'genesis',
             'Exo': 'exodus',
             'Lev': 'leviticus',
             'Deu': 'deuteronomy',
             'Sa1': 'samuel',
             'Sa2': 'samuel',
             'Kg1': 'kings',
             'Kg2': 'kings',
             'Dan': 'daniel',
             'Ch1': 'chronicles',
             'Ch2': 'chronicles',
             'Sol': 'song_of_songs',
             'Ezr': 'ezra-nehemiah',
             'Neh': 'ezra-nehemiah',
             'Ecc': 'ecclesiastes',
             'Jdg': 'judges',
             'Est': 'esther',
             'Jos': 'joshua'
             }
